name: smartkodes_app
description: SmartKodes mobile app - work orders, forms, notifications.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.20
  path: ^1.8.3
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  url_launcher: ^6.2.2
  open_filex: ^4.7.0
  image_picker: ^1.0.7
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  drift_dev: ^2.14.0
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon.png
  adaptive_icon_background: "#03045E"
  adaptive_icon_foreground: assets/icon.png
